name: Trigger auto deployment for album-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'dockerfile/**'
    - '.github/workflows/album-api-AutoDeployTrigger-6a9d27a9-6621-4da7-bd4d-222f49faf040.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: tscacasample.azurecr.io
          username: ${{ secrets.ALBUMAPI_REGISTRY_USERNAME }}
          password: ${{ secrets.ALBUMAPI_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: tscacasample.azurecr.io/album-api:${{ github.sha }}
          file: ./dockerfile/Dockerfile
          context: ./dockerfile/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ALBUMAPI_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n album-api -g tscaca-sample --server tscacasample.azurecr.io --username  ${{ secrets.ALBUMAPI_REGISTRY_USERNAME }} --password ${{ secrets.ALBUMAPI_REGISTRY_PASSWORD }}
            az containerapp update -n album-api -g tscaca-sample --image tscacasample.azurecr.io/album-api:${{ github.sha }}
